frontend:
  build: ../site/
  container_name: site
  env_file: './env'

api:
  build: ../api/
  container_name: api
  env_file: './env'

service1:
  build: ../service1/
  container_name: service1
  env_file: './env'

service2:
  build: ../service2/
  container_name: service2
  env_file: './env'
